-- 04_federal_tables.sql
-- Federal data tables (4 tables) - Hierarchy, awards, rates, exclusions

USE fed_contracts;

CREATE TABLE IF NOT EXISTS federal_organization (
    fh_org_id            INT NOT NULL,
    fh_org_name          VARCHAR(500),
    fh_org_type          VARCHAR(50),
    description          TEXT,
    status               VARCHAR(20),
    agency_code          VARCHAR(20),
    oldfpds_office_code  VARCHAR(20),
    cgac                 VARCHAR(10),
    parent_org_id        INT,
    level                INT,
    created_date         DATE,
    last_modified_date   DATE,
    record_hash          CHAR(64),
    first_loaded_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_loaded_at       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_load_id         INT,
    PRIMARY KEY (fh_org_id),
    INDEX idx_fh_parent (parent_org_id),
    INDEX idx_fh_agency (agency_code),
    INDEX idx_fh_type (fh_org_type),
    INDEX idx_fh_status (status),
    INDEX idx_fh_cgac (cgac),
    INDEX idx_fh_hash (record_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fpds_contract (
    contract_id          VARCHAR(50) NOT NULL,
    idv_piid             VARCHAR(50),
    modification_number  VARCHAR(10) NOT NULL DEFAULT '0',
    transaction_number   VARCHAR(10),
    agency_id            VARCHAR(10),
    agency_name          VARCHAR(200),
    contracting_office_id VARCHAR(20),
    contracting_office_name VARCHAR(200),
    funding_agency_id    VARCHAR(10),
    funding_agency_name  VARCHAR(200),
    vendor_uei           VARCHAR(12),
    vendor_name          VARCHAR(200),
    vendor_duns          VARCHAR(9),
    date_signed          DATE,
    effective_date       DATE,
    completion_date      DATE,
    last_modified_date   DATE,
    dollars_obligated    DECIMAL(15,2),
    base_and_all_options DECIMAL(15,2),
    naics_code           VARCHAR(6),
    psc_code             VARCHAR(10),
    set_aside_type       VARCHAR(20),
    type_of_contract     VARCHAR(10),
    description          TEXT,
    pop_state            VARCHAR(6),       -- ISO 3166-2 subdivision codes (e.g., IN-MH)
    pop_country          VARCHAR(3),
    pop_zip              VARCHAR(10),
    extent_competed      VARCHAR(10),
    number_of_offers     INT,
    far1102_exception_code   VARCHAR(2),
    far1102_exception_name   VARCHAR(100),
    reason_for_modification  VARCHAR(100),
    solicitation_date        DATE,
    ultimate_completion_date DATE,
    type_of_contract_pricing VARCHAR(10),
    co_bus_size_determination VARCHAR(50),
    record_hash              CHAR(64),
    first_loaded_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_loaded_at       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_load_id         INT,
    PRIMARY KEY (contract_id, modification_number),
    INDEX idx_fpds_vendor (vendor_uei),
    INDEX idx_fpds_naics (naics_code),
    INDEX idx_fpds_agency (agency_id),
    INDEX idx_fpds_date (date_signed),
    INDEX idx_fpds_setaside (set_aside_type),
    INDEX idx_fpds_completion (completion_date),
    INDEX idx_fpds_hash (record_hash),
    INDEX idx_fpds_far1102 (far1102_exception_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gsa_labor_rate (
    id                   INT AUTO_INCREMENT PRIMARY KEY,
    labor_category       VARCHAR(200),
    education_level      VARCHAR(50),
    min_years_experience INT,
    hourly_rate_year1    DECIMAL(10,2),
    current_price        DECIMAL(10,2),
    next_year_price      DECIMAL(10,2),
    second_year_price    DECIMAL(10,2),
    schedule             VARCHAR(200),
    contractor_name      VARCHAR(200),
    sin                  VARCHAR(500),
    business_size        VARCHAR(10),
    security_clearance   VARCHAR(50),
    worksite             VARCHAR(100),
    contract_start       DATE,
    contract_end         DATE,
    first_loaded_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_loaded_at       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_load_id         INT,
    INDEX idx_labor_category (labor_category),
    INDEX idx_labor_schedule (schedule),
    INDEX idx_labor_size (business_size)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sam_exclusion (
    id                   INT AUTO_INCREMENT PRIMARY KEY,
    uei                  VARCHAR(12),
    cage_code            VARCHAR(10),
    entity_name          VARCHAR(500),
    first_name           VARCHAR(100),
    middle_name          VARCHAR(100),
    last_name            VARCHAR(100),
    suffix               VARCHAR(20),
    prefix               VARCHAR(20),
    exclusion_type       VARCHAR(50),
    exclusion_program    VARCHAR(50),
    excluding_agency_code VARCHAR(10),
    excluding_agency_name VARCHAR(200),
    activation_date      DATE,
    termination_date     DATE,
    additional_comments  TEXT,
    record_hash          CHAR(64),
    first_loaded_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_load_id         INT,
    INDEX idx_excl_uei (uei),
    INDEX idx_excl_entity_name (entity_name),
    INDEX idx_excl_activation (activation_date),
    INDEX idx_excl_type (exclusion_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
