export const queryKeys = {
  opportunities: {
    all: ['opportunities'] as const,
    list: (params: Record<string, unknown>) => ['opportunities', 'list', params] as const,
    detail: (noticeId: string) => ['opportunities', 'detail', noticeId] as const,
    targets: (params: Record<string, unknown>) => ['opportunities', 'targets', params] as const,
    pwin: (noticeId: string) => ['opportunities', 'pwin', noticeId] as const,
    pwinBatch: (noticeIds: string[]) => ['opportunities', 'pwin', 'batch', ...noticeIds] as const,
    qualification: (noticeId: string) => ['opportunities', 'qualification', noticeId] as const,
    incumbent: (noticeId: string) => ['opportunities', 'incumbent', noticeId] as const,
    recommended: (limit: number) => ['opportunities', 'recommended', limit] as const,
    ignoredIds: () => ['opportunities', 'ignoredIds'] as const,
    competitiveLandscape: (noticeId: string) => ['opportunities', 'competitiveLandscape', noticeId] as const,
    setAsideShift: (noticeId: string) => ['opportunities', 'setAsideShift', noticeId] as const,
    documentIntelligence: (noticeId: string) => ['opportunities', 'documentIntelligence', noticeId] as const,
    analysisStatus: (noticeId: string) => ['opportunities', 'analysisStatus', noticeId] as const,
    ivs: (noticeId: string) => ['opportunities', 'ivs', noticeId] as const,
    competitors: (noticeId: string) => ['opportunities', 'competitors', noticeId] as const,
    marketCompetitors: (naicsCode: string) => ['opportunities', 'marketCompetitors', naicsCode] as const,
    competitorDetail: (uei: string) => ['opportunities', 'competitorDetail', uei] as const,
    partners: (noticeId: string) => ['opportunities', 'partners', noticeId] as const,
    partnerScore: (noticeId: string, partnerUei: string) => ['opportunities', 'partnerScore', noticeId, partnerUei] as const,
    openDoorPrimes: (naicsCode: string) => ['opportunities', 'openDoorPrimes', naicsCode] as const,
    openDoorPrime: (primeUei: string) => ['opportunities', 'openDoorPrime', primeUei] as const,
    pursuitPriority: (noticeId: string) => ['opportunities', 'pursuitPriority', noticeId] as const,
  },
  awards: {
    all: ['awards'] as const,
    list: (params: Record<string, unknown>) => ['awards', 'list', params] as const,
    detail: (contractId: string) => ['awards', 'detail', contractId] as const,
    burnRate: (contractId: string) => ['awards', 'burnRate', contractId] as const,
    marketShare: (naicsCode: string) => ['awards', 'marketShare', naicsCode] as const,
    expiring: (params: Record<string, unknown>) => ['awards', 'expiring', params] as const,
    setAsideTrends: (naicsCode: string) => ['awards', 'setAsideTrends', naicsCode] as const,
    loadStatus: (contractId: string) => ['awards', 'load-status', contractId] as const,
  },
  entities: {
    all: ['entities'] as const,
    list: (params: Record<string, unknown>) => ['entities', 'list', params] as const,
    detail: (uei: string) => ['entities', 'detail', uei] as const,
    competitor: (uei: string) => ['entities', 'competitor', uei] as const,
    exclusions: (uei: string) => ['entities', 'exclusions', uei] as const,
  },
  subawards: {
    all: ['subawards'] as const,
    teamingPartners: (params: Record<string, unknown>) =>
      ['subawards', 'teamingPartners', params] as const,
    byPrime: (primePiid: string) => ['subawards', 'byPrime', primePiid] as const,
  },
  prospects: {
    all: ['prospects'] as const,
    list: (params: Record<string, unknown>) => ['prospects', 'list', params] as const,
    detail: (id: number) => ['prospects', 'detail', id] as const,
  },
  proposals: {
    all: ['proposals'] as const,
    list: (params: Record<string, unknown>) => ['proposals', 'list', params] as const,
    milestones: (proposalId: number) => ['proposals', 'milestones', proposalId] as const,
  },
  dashboard: {
    all: ['dashboard'] as const,
  },
  savedSearches: {
    all: ['savedSearches'] as const,
    list: ['savedSearches', 'list'] as const,
    detail: (id: number) => ['savedSearches', 'detail', id] as const,
    run: (id: number) => ['savedSearches', 'run', id] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    list: (params: Record<string, unknown>) => ['notifications', 'list', params] as const,
    unreadCount: ['notifications', 'unreadCount'] as const,
  },
  admin: {
    all: ['admin'] as const,
    etlStatus: ['admin', 'etlStatus'] as const,
    users: (params?: Record<string, unknown>) => ['admin', 'users', params] as const,
    loadHistory: (params?: Record<string, unknown>) => ['admin', 'loadHistory', params] as const,
    health: ['admin', 'health'] as const,
    organizations: ['admin', 'organizations'] as const,
  },
  organization: {
    all: ['organization'] as const,
    details: ['organization', 'details'] as const,
    profile: ['organization', 'profile'] as const,
    naics: ['organization', 'naics'] as const,
    certifications: ['organization', 'certifications'] as const,
    entities: ['organization', 'entities'] as const,
    pastPerformance: ['organization', 'pastPerformance'] as const,
    members: ['organization', 'members'] as const,
    invites: ['organization', 'invites'] as const,
  },
  reference: {
    naics: (query: string) => ['reference', 'naics', query] as const,
    naicsDetail: (code: string) => ['reference', 'naics', 'detail', code] as const,
    certificationTypes: ['reference', 'certificationTypes'] as const,
  },
  hierarchy: {
    all: ['hierarchy'] as const,
    list: (params: Record<string, unknown>) => ['hierarchy', 'list', params] as const,
    detail: (fhOrgId: string) => ['hierarchy', 'detail', fhOrgId] as const,
    children: (fhOrgId: string, status?: string, keyword?: string) => ['hierarchy', 'children', fhOrgId, status ?? '', keyword ?? ''] as const,
    tree: (keyword?: string) => ['hierarchy', 'tree', keyword ?? ''] as const,
    opportunities: (fhOrgId: string, params?: Record<string, unknown>) => ['hierarchy', 'opportunities', fhOrgId, params] as const,
    refreshStatus: ['hierarchy', 'refreshStatus'] as const,
    lookup: (name?: string, agencyCode?: string) =>
      ['hierarchy', 'lookup', name ?? '', agencyCode ?? ''] as const,
  },
  pricing: {
    all: ['pricing'] as const,
    categories: (group?: string) => ['pricing', 'categories', group ?? ''] as const,
    categorySearch: (query: string) => ['pricing', 'categories', 'search', query] as const,
    heatmap: (params: Record<string, unknown>) => ['pricing', 'heatmap', params] as const,
    distribution: (canonicalId: number) => ['pricing', 'distribution', canonicalId] as const,
    subBenchmarks: (params: Record<string, unknown>) => ['pricing', 'subBenchmarks', params] as const,
    subRatios: (naicsCode?: string) => ['pricing', 'subRatios', naicsCode ?? ''] as const,
    rateTrends: (canonicalId: number, years?: number) => ['pricing', 'rateTrends', canonicalId, years ?? 5] as const,
    escalation: (canonicalId: number, years?: number) => ['pricing', 'escalation', canonicalId, years ?? 5] as const,
    scaRateRange: (params: Record<string, unknown>) => ['pricing', 'scaRateRange', params] as const,
    scaOccupations: () => ['pricing', 'scaOccupations'] as const,
    scaAreaRates: (params: Record<string, unknown>) => ['pricing', 'scaAreaRates', params] as const,
  },
  competitiveIntel: {
    all: ['competitiveIntel'] as const,
    recompetes: (params: Record<string, unknown>) => ['competitiveIntel', 'recompetes', params] as const,
    agencyPatterns: (params: Record<string, unknown>) => ['competitiveIntel', 'agencyPatterns', params] as const,
    buyingPatterns: (agencyCode: string, year?: number) => ['competitiveIntel', 'buyingPatterns', agencyCode, year ?? 0] as const,
    competitorDossier: (uei: string) => ['competitiveIntel', 'competitorDossier', uei] as const,
    offices: (params: Record<string, unknown>) => ['competitiveIntel', 'offices', params] as const,
    officeProfile: (officeCode: string) => ['competitiveIntel', 'officeProfile', officeCode] as const,
  },
  pipeline: {
    all: ['pipeline'] as const,
    funnel: ['pipeline', 'funnel'] as const,
    calendar: (startDate: string, endDate: string) => ['pipeline', 'calendar', startDate, endDate] as const,
    stale: ['pipeline', 'stale'] as const,
    forecast: ['pipeline', 'forecast'] as const,
    milestones: (prospectId: number) => ['pipeline', 'milestones', prospectId] as const,
  },
  teaming: {
    all: ['teaming'] as const,
    partners: (params: Record<string, unknown>) => ['teaming', 'partners', params] as const,
    partnerRisk: (uei: string) => ['teaming', 'partnerRisk', uei] as const,
    relationships: (uei: string, page?: number) => ['teaming', 'relationships', uei, page ?? 1] as const,
    network: (uei: string, depth?: number) => ['teaming', 'network', uei, depth ?? 1] as const,
    mentorProtege: (params: Record<string, unknown>) => ['teaming', 'mentorProtege', params] as const,
    gapAnalysis: (naicsCode?: string) => ['teaming', 'gapAnalysis', naicsCode ?? ''] as const,
  },
  onboarding: {
    all: ['onboarding'] as const,
    profileCompleteness: ['onboarding', 'profileCompleteness'] as const,
    certificationAlerts: ['onboarding', 'certificationAlerts'] as const,
    sizeStandardAlerts: ['onboarding', 'sizeStandardAlerts'] as const,
    pastPerformanceRelevance: (noticeId?: string) => ['onboarding', 'pastPerformanceRelevance', noticeId ?? ''] as const,
    portfolioGaps: ['onboarding', 'portfolioGaps'] as const,
    pscCodes: ['onboarding', 'pscCodes'] as const,
  },
  insights: {
    all: ['insights'] as const,
    similar: (noticeId: string, maxResults?: number) => ['insights', 'similar', noticeId, maxResults ?? 20] as const,
    dataQuality: ['insights', 'dataQuality'] as const,
    prospectCompetitor: (prospectId: number) => ['insights', 'prospectCompetitor', prospectId] as const,
    prospectCompetitors: (prospectIds: number[]) => ['insights', 'prospectCompetitors', ...prospectIds] as const,
  },
  auth: {
    me: ['auth', 'me'] as const,
  },
} as const;
