// <auto-generated />
// This snapshot is maintained manually alongside the AddRefreshTokenHash migration.
// It records the state of the EF Core model after that migration is applied.
// Run `dotnet ef migrations add <Name>` to auto-regenerate after further changes.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FedProspector.Infrastructure.Data;

#nullable disable

namespace FedProspector.Infrastructure.Migrations;

[DbContext(typeof(FedProspectorDbContext))]
partial class FedProspectorDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("FedProspector.Core.Models.AppSession", b =>
        {
            b.Property<int>("SessionId")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<DateTime>("ExpiresAt")
                .HasColumnType("datetime(6)");

            b.Property<string>("IpAddress")
                .HasMaxLength(45)
                .HasColumnType("varchar(45)");

            b.Property<DateTime>("IssuedAt")
                .HasColumnType("datetime(6)");

            b.Property<string>("RefreshTokenHash")
                .HasMaxLength(64)
                .HasColumnType("varchar(64)")
                .HasColumnName("refresh_token_hash");

            b.Property<DateTime?>("RevokedAt")
                .HasColumnType("datetime(6)");

            b.Property<string>("RevokedReason")
                .HasMaxLength(100)
                .HasColumnType("varchar(100)");

            b.Property<string>("TokenHash")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("varchar(64)");

            b.Property<string>("UserAgent")
                .HasMaxLength(500)
                .HasColumnType("varchar(500)");

            b.Property<int>("UserId")
                .HasColumnType("int");

            b.HasKey("SessionId");

            b.HasIndex("RefreshTokenHash")
                .HasDatabaseName("IX_app_session_refresh_token_hash");

            b.HasIndex("TokenHash")
                .IsUnique();

            b.HasIndex("UserId");

            b.ToTable("app_session");
        });
#pragma warning restore 612, 618
    }
}
